# Generated by Django 4.2.6 on 2023-10-29 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'ordering': ['fname']},
        ),
    ]
