# Generated by Django 4.0 on 2023-11-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_sign_up'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sign_up',
            options={'ordering': ['name']},
        ),
    ]
