# Generated by Django 4.0 on 2023-11-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_sign_up_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sign_up',
            options={'ordering': ['username']},
        ),
        migrations.RenameField(
            model_name='sign_up',
            old_name='name',
            new_name='username',
        ),
    ]
